
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Cmake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/Cmake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Cmake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Cmake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
      生成启动时间为 2024/2/21 16:44:03。
      
      节点 1 上的项目“C:\\Users\\18143\\Desktop\\hello\\build\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdC.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        正在对“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”执行 Touch 任务。
      ClCompile:
        D:\\vscommunity\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        D:\\vscommunity\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\18143\\Desktop\\hello\\build\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=D:\\vscommunity\\VC\\Tools\\MSVC\\14.34.31933\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate”执行 Touch 任务。
      已完成生成项目“C:\\Users\\18143\\Desktop\\hello\\build\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:01.08
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/18143/Desktop/hello/build/CMakeFiles/3.28.1/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Cmake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Cmake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Cmake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
      生成启动时间为 2024/2/21 16:44:04。
      
      节点 1 上的项目“C:\\Users\\18143\\Desktop\\hello\\build\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdCXX.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        正在对“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”执行 Touch 任务。
      ClCompile:
        D:\\vscommunity\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        D:\\vscommunity\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\18143\\Desktop\\hello\\build\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=D:\\vscommunity\\VC\\Tools\\MSVC\\14.34.31933\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate”执行 Touch 任务。
      已完成生成项目“C:\\Users\\18143\\Desktop\\hello\\build\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:00.94
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/18143/Desktop/hello/build/CMakeFiles/3.28.1/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Cmake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/Cmake/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/18143/Desktop/hello/build/CMakeFiles/CMakeScratch/TryCompile-snaccb"
      binary: "C:/Users/18143/Desktop/hello/build/CMakeFiles/CMakeScratch/TryCompile-snaccb"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/18143/Desktop/hello/build/CMakeFiles/CMakeScratch/TryCompile-snaccb'
        
        Run Build Command(s): D:/vscommunity/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_5e458.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
        生成启动时间为 2024/2/21 16:44:05。
        
        节点 1 上的项目“C:\\Users\\18143\\Desktop\\hello\\build\\CMakeFiles\\CMakeScratch\\TryCompile-snaccb\\cmTC_5e458.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_5e458.dir\\Debug\\”。
          正在创建目录“C:\\Users\\18143\\Desktop\\hello\\build\\CMakeFiles\\CMakeScratch\\TryCompile-snaccb\\Debug\\”。
          正在创建目录“cmTC_5e458.dir\\Debug\\cmTC_5e458.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_5e458.dir\\Debug\\cmTC_5e458.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
          正在对“cmTC_5e458.dir\\Debug\\cmTC_5e458.tlog\\unsuccessfulbuild”执行 Touch 任务。
        ClCompile:
          D:\\vscommunity\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_5e458.dir\\Debug\\\\" /Fd"cmTC_5e458.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "D:\\Cmake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.34.31947 版
          版权所有(C) Microsoft Corporation。保留所有权利。
          CMakeCCompilerABI.c
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_5e458.dir\\Debug\\\\" /Fd"cmTC_5e458.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "D:\\Cmake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
        Link:
          D:\\vscommunity\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\18143\\Desktop\\hello\\build\\CMakeFiles\\CMakeScratch\\TryCompile-snaccb\\Debug\\cmTC_5e458.exe" /INCREMENTAL /ILK:"cmTC_5e458.dir\\Debug\\cmTC_5e458.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/18143/Desktop/hello/build/CMakeFiles/CMakeScratch/TryCompile-snaccb/Debug/cmTC_5e458.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/18143/Desktop/hello/build/CMakeFiles/CMakeScratch/TryCompile-snaccb/Debug/cmTC_5e458.lib" /MACHINE:X64  /machine:x64 cmTC_5e458.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_5e458.vcxproj -> C:\\Users\\18143\\Desktop\\hello\\build\\CMakeFiles\\CMakeScratch\\TryCompile-snaccb\\Debug\\cmTC_5e458.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_5e458.dir\\Debug\\cmTC_5e458.tlog\\unsuccessfulbuild”。
          正在对“cmTC_5e458.dir\\Debug\\cmTC_5e458.tlog\\cmTC_5e458.lastbuildstate”执行 Touch 任务。
        已完成生成项目“C:\\Users\\18143\\Desktop\\hello\\build\\CMakeFiles\\CMakeScratch\\TryCompile-snaccb\\cmTC_5e458.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:00.65
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Cmake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/Cmake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/18143/Desktop/hello/build/CMakeFiles/CMakeScratch/TryCompile-p34h5h"
      binary: "C:/Users/18143/Desktop/hello/build/CMakeFiles/CMakeScratch/TryCompile-p34h5h"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/18143/Desktop/hello/build/CMakeFiles/CMakeScratch/TryCompile-p34h5h'
        
        Run Build Command(s): D:/vscommunity/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_55fac.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
        生成启动时间为 2024/2/21 16:44:06。
        
        节点 1 上的项目“C:\\Users\\18143\\Desktop\\hello\\build\\CMakeFiles\\CMakeScratch\\TryCompile-p34h5h\\cmTC_55fac.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_55fac.dir\\Debug\\”。
          正在创建目录“C:\\Users\\18143\\Desktop\\hello\\build\\CMakeFiles\\CMakeScratch\\TryCompile-p34h5h\\Debug\\”。
          正在创建目录“cmTC_55fac.dir\\Debug\\cmTC_55fac.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_55fac.dir\\Debug\\cmTC_55fac.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
          正在对“cmTC_55fac.dir\\Debug\\cmTC_55fac.tlog\\unsuccessfulbuild”执行 Touch 任务。
        ClCompile:
          D:\\vscommunity\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_55fac.dir\\Debug\\\\" /Fd"cmTC_55fac.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "D:\\Cmake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.34.31947 版
          CMakeCXXCompilerABI.cpp
          版权所有(C) Microsoft Corporation。保留所有权利。
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_55fac.dir\\Debug\\\\" /Fd"cmTC_55fac.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "D:\\Cmake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          D:\\vscommunity\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\18143\\Desktop\\hello\\build\\CMakeFiles\\CMakeScratch\\TryCompile-p34h5h\\Debug\\cmTC_55fac.exe" /INCREMENTAL /ILK:"cmTC_55fac.dir\\Debug\\cmTC_55fac.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/18143/Desktop/hello/build/CMakeFiles/CMakeScratch/TryCompile-p34h5h/Debug/cmTC_55fac.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/18143/Desktop/hello/build/CMakeFiles/CMakeScratch/TryCompile-p34h5h/Debug/cmTC_55fac.lib" /MACHINE:X64  /machine:x64 cmTC_55fac.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_55fac.vcxproj -> C:\\Users\\18143\\Desktop\\hello\\build\\CMakeFiles\\CMakeScratch\\TryCompile-p34h5h\\Debug\\cmTC_55fac.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_55fac.dir\\Debug\\cmTC_55fac.tlog\\unsuccessfulbuild”。
          正在对“cmTC_55fac.dir\\Debug\\cmTC_55fac.tlog\\cmTC_55fac.lastbuildstate”执行 Touch 任务。
        已完成生成项目“C:\\Users\\18143\\Desktop\\hello\\build\\CMakeFiles\\CMakeScratch\\TryCompile-p34h5h\\cmTC_55fac.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:00.71
        
      exitCode: 0
...
